In [1]:
from numpy import exp, array , random, dot

In [2]:
training_set_inputs= array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
training_set_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [3]:
training_set_outs= array([[0,1,1,0]]).T
training_set_outs

array([[0],
       [1],
       [1],
       [0]])

In [4]:
random.seed(2017)

In [5]:
synaptic_weights =  2*random.random((3,1))-1
synaptic_weights


array([[-0.95807955],
       [ 0.53414033],
       [-0.1041604 ]])

In [6]:
dot(training_set_inputs,synaptic_weights)

array([[-0.1041604 ],
       [-0.52809962],
       [-1.06223995],
       [ 0.42997993]])

In [10]:
for iteration in range(500):
    output = 1 / (1 + exp(-(dot(training_set_inputs,synaptic_weights))))
    #print("Output : \n" , output)
    synaptic_weights += dot(training_set_inputs.T,(training_set_outs-output) * (1-output))
    #print("synaptic_weights : \n", synaptic_weights)

print()
print(1/(1 + exp(-(dot(array([1,0,0]),synaptic_weights)))))   


[ 0.99996538]
